---

- name: install extensions
  apt:
    deb: https://ftp.weheartwebsites.de/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/php{{ php7cli_majorminor_version }}/php{{ php7cli_majorminor_version }}-{{ item }}_amd64.deb
  with_items:
    - libsodium_{{ php7cli_ext_libsodium_version }}
    - apcu_{{ php7cli_ext_apcu_version }}
    - apcu-bc_{{ php7cli_ext_apcu_bc_version }}
    - imagick_{{ php7cli_ext_imagick_version }}
    - igbinary_{{ php7cli_ext_igbinary_version }}
    - redis_{{ php7cli_ext_redis_version }}
    - iredis_{{ php7cli_ext_iredis_version }}
    - memcached_{{ php7cli_ext_memcached_version }}
    - geoip_{{ php7cli_ext_geoip_version }}
  become: yes
